### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by cxqiscool** [ASE-group10/dsw-frontend#2]
➜  route-calculation-service git:(f6d49d1) npm install
(node:11272) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code ENOENT
npm error syscall open
npm error path /Users/caixinqi/ASE/dsw-backend/route-calculation-service/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/caixinqi/ASE/dsw-backend/route-calculation-service/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/caixinqi/.npm/_logs/2024-11-25T16_37_41_437Z-debug-0.log
➜  route-calculation-service git:(f6d49d1) ✗

**Comment by cxqiscool** [comment]
@ZeYanLiow plz have a look

**Comment by cosmopolitan033** [comment]
@ZeYanLiow plz have a look

**Comment by ZeYanLiow** [comment]
Oh, when I set up the project, I chose Yarn over npm, so there’s no package-lock.json, only yarn.lock. Try using **'yarn install'** instead. I will update the README file now.
